# Generated by Django 3.2.7 on 2021-10-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='written_cover_letter',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
