# Generated by Django 3.2.8 on 2021-10-17 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0002_auto_20211013_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('Не ищу работу', 'Не ищу работу'), ('Рассматриваю предложения', 'Рассматриваю предложения'), ('Ищу работу', 'Ищу работу')], max_length=32)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(choices=[('Стажер', 'Стажер'), ('Джуниор', 'Джуниор'), ('Миддл', 'Миддл'), ('Синьор', 'Синьор'), ('Лид', 'Лид')], max_length=16)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.CharField(max_length=64)),
                ('specialty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacancies.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
